### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by divramod** [RisingStack/graffiti-mongoose#80]
hey, while running npm install i get the following error. do i have the wrong node version?

```
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12

npm ERR! Invalid name: "@risingstack/graffiti-mongoose"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mod-new/code/test/graffiti-mongoose/example/npm-debug.log
```

**Comment by tothandras** [comment]
I've tried to run `npm install @risingstack/graffiti-mongoose` with version 3.3.12, no error. Try to reinstall node and/or npm and repair permissions with running `chown -R [yourname] ~/.npm`.

**Comment by divramod** [comment]
thx, i updated npm and it is installing.
now i got the following error:
```
> $ npm install                                                                                                                                                                         [±master]
npm WARN install Couldn't install optional dependency: Unsupported

> pre-commit@1.1.2 install /home/mod-new/code/test/graffiti-mongoose/node_modules/pre-commit
> node install.js


> spawn-sync@1.0.13 postinstall /home/mod-new/code/test/graffiti-mongoose/node_modules/spawn-sync
> node postinstall


> @risingstack/graffiti-mongoose@5.0.3 prepublish /home/mod-new/code/test/graffiti-mongoose
> npm test && npm run build


> @risingstack/graffiti-mongoose@5.0.3 test /home/mod-new/code/test/graffiti-mongoose
> NODE_ENV=test mocha --compilers js:babel-register --require babel-polyfill 'src/**/*.spec.js'



  1) "before all" hook

  0 passing (152ms)
  1 failing

  1)  "before all" hook:
     MongoError: topology was destroyed
      at node_modules/mongodb/lib/db.js:799:78
      at executeCommand (node_modules/mongodb/lib/db.js:261:67)
      at [object Object].Db.command (node_modules/mongodb/lib/db.js:306:44)
      at [object Object].Db.dropDatabase (node_modules/mongodb/lib/db.js:797:49)
      at setup-tests.spec.js:13:28
      at NativeConnection.Connection.error (node_modules/mongoose/lib/connection.js:424:24)
      at node_modules/mongoose/lib/connection.js:452:14
      at node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:58:21
      at node_modules/mongodb/lib/db.js:224:14
      at [object Object].<anonymous> (node_modules/mongodb/lib/server.js:234:9)
      at [object Object].<anonymous> (node_modules/mongodb-core/lib/topologies/server.js:269:68)
      at [object Object].<anonymous> (node_modules/mongodb-core/lib/connection/pool.js:81:12)
      at Socket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:124:49)
      at emitErrorNT (net.js:1257:8)



npm ERR! Test failed.  See above for more details.

npm WARN EPEERINVALID mongodb-core@1.2.30 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @risingstack/graffiti-mongoose@5.0.3 prepublish: `npm test && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @risingstack/graffiti-mongoose@5.0.3 prepublish script 'npm test && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @risingstack/graffiti-mongoose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls @risingstack/graffiti-mongoose
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by tothandras** [comment]
@divramod `npm prepublish` has an error, so it runs the whole e2e test on install. Keep the mongo daemon running.

**Comment by tothandras** [comment]
@divramod Did you manage to solve the problem?

**Comment by divramod** [comment]
Yes thx
